# Generated by Django 3.2.3 on 2021-06-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='psitions',
            new_name='positions',
        ),
    ]
